const addressesData = [
  {
    id: 1,
    city: "istanbul",
    district: "Kadıköy",
    neighborhood: "Osmanağa Mh.",
    street: "Kırtasiyeci Sk.",
    gatenumber: 13,
  },
  {
    id: 2,
    city: "İstanbul",
    district: "Beyoğlu",
    neighborhood: "Gümüşsuyu Mahallesi",
    street: "Mete Caddesi",
    gatenumber: 2,
  },
  {
    id: 3,
    city: "Ankara",
    district: "Çankaya",
    neighborhood: "Mustafa Kemal Mahallesi",
    street: "Dumlupınar Bulvarı",
    gatenumber: 109,
  },
  {
    id: 4,
    city: "Samsun",
    district: "Atakum",
    neighborhood: "Körfez Mahallesi",
    street: null,
    gatenumber: null,
  },
  {
    id: 5,
    city: "Ankara",
    district: "Çankaya",
    neighborhood: "Kavaklıdere Mahallesi",
    street: "Tunus Caddesi",
    gatenumber: 14,
  },
  {
    id: 6,
    city: "İstanbul",
    district: "Üsküdar",
    neighborhood: "Selamiali Mahallesi",
    street: "Vakıf Sokak",
    gatenumber: 8,
  },
  {
    id: 7,
    city: "Ankara",
    district: "Altındağ",
    neighborhood: "Talatpaşa Bulvarı",
    street: null,
    gatenumber: 38,
  },
  {
    id: 8,
    city: "İstanbul",
    district: "Beyoğlu",
    neighborhood: "Kuloğlu Mahallaesi",
    street: "İstiklâl Caddesi",
    gatenumber: 24,
  },
  {
    id: 9,
    city: "İzmir",
    district: "Konak",
    neighborhood: "Mimar Sinan Mahallaesi",
    street: "Ali Çetinkaya Bulvarı",
    gatenumber: 75,
  },
  {
    id: 10,
    city: "Ankara",
    district: "Çankaya",
    neighborhood: "Yukarı Bahçelievler Mahallaesi",
    street: "Aşkabat Caddesi (7.Cadde)",
    gatenumber: null,
  },
  {
    id: 11,
    city: "Ankara",
    district: "Yenimahalle",
    neighborhood: "Kardelen Mahallesi",
    street: "Başkent Bulvarı",
    gatenumber: 224,
  },
];
export default addressesData;
