const placesData = [
  {
    id: 1,
    name: "CSO",
    interior: true,
    seatcapacity: 1300,
    standcapacity: 0,
    AddressId: 7,
  },
  {
    id: 2,
    name: "Muaf Kadıköy",
    interior: true,
    seatcapacity: 100,
    standcapacity: 0,
    AddressId: 1,
  },
  {
    id: 3,
    name: "Ankara Paribu Cineverse (Atlantis)",
    interior: true,
    seatcapacity: 100,
    standcapacity: 0,
    AddressId: 11,
  },
  {
    id: 4,
    name: "Ankara Büyülü Fener Bahçelievler",
    interior: true,
    seatcapacity: 120,
    standcapacity: 0,
    AddressId: 10,
  },
  {
    id: 5,
    name: "Ankara Prestige (Kentpark)",
    interior: true,
    seatcapacity: 150,
    standcapacity: 0,
    AddressId: 3,
  },
  {
    id: 6,
    name: "Vakıfbank Spor Sarayı",
    interior: true,
    seatcapacity: 120,
    standcapacity: 0,
    AddressId: 6,
  },
  {
    id: 7,
    name: "Türk Telekom Opera Salonu",
    interior: true,
    seatcapacity: 1000,
    standcapacity: 0,
    AddressId: 2,
  },
  {
    id: 8,
    name: "Mehmet Yalçın Taşpektepligil Kapalı Spor Salonu",
    interior: true,
    seatcapacity: 5000,
    standcapacity: 0,
    AddressId: 4,
  },
  {
    id: 9,
    name: "TVF Atatürk Voleybol Salonu Vestel Spor Kompleksi",
    interior: true,
    seatcapacity: 10000,
    standcapacity: 0,
    AddressId: 9,
  },
  {
    id: 10,
    name: "IF Ankara Performance Hall",
    interior: true,
    seatcapacity: 700,
    standcapacity: 0,
    AddressId: 5,
  },
  {
    id: 11,
    name: "Efsahne Beyoğlu",
    interior: true,
    seatcapacity: 100,
    standcapacity: 0,
    AddressId: 8,
  },
];
export default placesData;
